### ISSUE TITLE
Config and deploy new alpha package on PyPI

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#83]
Am halfway through, some notes-to-self:

- [x] makefile config working
- [x] package uploads to https://test.pypi.org/project/cltkv1/
- [x] package install works from test pypi
- [ ] ~add dependencies to poetry.toml (?); error from downloaded package:~

``` python
Python 3.7.5 (default, Oct 31 2019, 20:57:45) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cltkv1 import NLP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltkv1/__init__.py", line 3, in <module>
    from .nlp import NLP
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltkv1/nlp.py", line 11, in <module>
    from cltkv1.core.data_types import Doc, Language, Pipeline
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltkv1/core/__init__.py", line 1, in <module>
    from .data_types import *
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltkv1/core/data_types.py", line 15, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

- [x] change all namespaces to cltk
- [x] build local
- [x] push to cltk on test pypi
- [x] tests pass on build server ( #85 )
- [x] pip install and validate pre-release on real pypi

At this point, I may be ready to open up a new branch in our main repo, then move all these tickets to it.

**Comment by kylepjohnson** [comment]
The doctest build passes: https://travis-ci.org/github/cltk/cltkv1/jobs/704358751

Waiting on the full suite

**Comment by kylepjohnson** [comment]
This is proceeding OK. Pushed to the real pypi: https://pypi.org/manage/project/cltk/release/1.0.0a4/

and the the usual command (`$ pip install cltk`) gets the old v0.1, while this gets the new:`$ pip install --pre cltk` with everything installed:

``` bash
$ pyenv virtualenv 3.7.5 pypitest
Looking in links: /var/folders/q7/hk37xg790572djtxl6_xb1xc0000gn/T/tmpydv6ljey
Requirement already satisfied: setuptools in /Users/kyle.p.johnson/.pyenv/versions/3.7.5/envs/pypitest/lib/python3.7/site-packages (41.2.0)
Requirement already satisfied: pip in /Users/kyle.p.johnson/.pyenv/versions/3.7.5/envs/pypitest/lib/python3.7/site-packages (19.2.3)
(pypitest) AMAC02Z92FELVCG:~ kyle.p.johnson$ python --version
Python 3.7.5
(pypitest) AMAC02Z92FELVCG:~ kyle.p.johnson$ pip install --pre cltk
Collecting cltk
  Using cached https://files.pythonhosted.org/packages/8a/12/ef830798d5b6aed4e9f95f97941be2043df603f8a32e6c707a6834e4a9c4/cltk-1.0.0a4-py3-none-any.whl
Collecting toml<0.11.0,>=0.10.1 (from cltk)
  Using cached https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
Collecting nltk<4.0,>=3.5 (from cltk)
Collecting requests<3.0.0,>=2.22.0 (from cltk)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting tqdm<5.0.0,>=4.41.1 (from cltk)
  Using cached https://files.pythonhosted.org/packages/46/62/7663894f67ac5a41a0d8812d78d9d2a9404124051885af9d77dc526fb399/tqdm-4.47.0-py2.py3-none-any.whl
Collecting fasttext<0.10.0,>=0.9.1 (from cltk)
Collecting boltons<21.0.0,>=20.0.0 (from cltk)
  Using cached https://files.pythonhosted.org/packages/b7/bd/93857bb50b65bad72d38d8af6d6600617a4b2c61312fa39bf688893d64c9/boltons-20.2.0-py2.py3-none-any.whl
Collecting greek-accentuation<2.0.0,>=1.2.0 (from cltk)
  Using cached https://files.pythonhosted.org/packages/be/91/cb02996626f43c2adbd2a6e964ddf3b5893a8ee5c2134a5dac66dd70306e/greek_accentuation-1.2.0-py2.py3-none-any.whl
Collecting gensim<4.0.0,>=3.8.1 (from cltk)
  Using cached https://files.pythonhosted.org/packages/70/cf/87b25b265d23498b2b70ce873495cf7ef91394c4baff240210e26f3bc18a/gensim-3.8.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting python-Levenshtein<0.13.0,>=0.12.0 (from cltk)
Collecting stanza<2.0.0,>=1.0.0 (from cltk)
  Using cached https://files.pythonhosted.org/packages/27/9c/60689521a971a57dd02d2925105efedefa9dccd76c9a0b92566683d43e89/stanza-1.0.1-py3-none-any.whl
Collecting gitpython<4.0,>=3.0 (from cltk)
  Using cached https://files.pythonhosted.org/packages/8c/f9/c315aa88e51fabdc08e91b333cfefb255aff04a2ee96d632c32cb19180c9/GitPython-3.1.3-py3-none-any.whl
Collecting joblib (from nltk<4.0,>=3.5->cltk)
  Using cached https://files.pythonhosted.org/packages/51/dd/0e015051b4a27ec5a58b02ab774059f3289a94b0906f880a3f9507e74f38/joblib-0.16.0-py3-none-any.whl
Collecting regex (from nltk<4.0,>=3.5->cltk)
Collecting click (from nltk<4.0,>=3.5->cltk)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests<3.0.0,>=2.22.0->cltk)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0.0,>=2.22.0->cltk)
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.22.0->cltk)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests<3.0.0,>=2.22.0->cltk)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting numpy (from fasttext<0.10.0,>=0.9.1->cltk)
  Using cached https://files.pythonhosted.org/packages/5c/f5/0e5e57fa7683cf0e5036320f4676cd7e3dbd9ab8c17ada541c2bb5ebed5e/numpy-1.19.0-cp37-cp37m-macosx_10_9_x86_64.whl
Requirement already satisfied: setuptools>=0.7.0 in ./.pyenv/versions/3.7.5/envs/pypitest/lib/python3.7/site-packages (from fasttext<0.10.0,>=0.9.1->cltk) (41.2.0)
Collecting pybind11>=2.2 (from fasttext<0.10.0,>=0.9.1->cltk)
  Using cached https://files.pythonhosted.org/packages/89/e3/d576f6f02bc75bacbc3d42494e8f1d063c95617d86648dba243c2cb3963e/pybind11-2.5.0-py2.py3-none-any.whl
Collecting six>=1.5.0 (from gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting scipy>=0.18.1 (from gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/11/b9/a79caafbd276b920ef2692b4b8602cc9cd9bd078f8c726d254354be2c2cb/scipy-1.5.0-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting smart-open>=1.8.1 (from gensim<4.0.0,>=3.8.1->cltk)
Collecting torch>=1.3.0 (from stanza<2.0.0,>=1.0.0->cltk)
  Using cached https://files.pythonhosted.org/packages/5d/ad/51da3af99a515c31226f50c37d85e63423f9e28174c2984e11e4fb47ae01/torch-1.5.1-cp37-none-macosx_10_9_x86_64.whl
Collecting protobuf (from stanza<2.0.0,>=1.0.0->cltk)
  Using cached https://files.pythonhosted.org/packages/12/b5/9347e30e11c040f5ca24f079d6f06485280c49b2a9f894b5400e27d4d6d1/protobuf-3.12.2-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting gitdb<5,>=4.0.1 (from gitpython<4.0,>=3.0->cltk)
  Using cached https://files.pythonhosted.org/packages/48/11/d1800bca0a3bae820b84b7d813ad1eff15a48a64caea9c823fc8c1b119e8/gitdb-4.0.5-py3-none-any.whl
Collecting boto3 (from smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/7e/e9/75f4db5ef020f4c12f05fcfb709c0c9db35aae912d7e90ee3ced3e7e04ad/boto3-1.14.16-py2.py3-none-any.whl
Collecting boto (from smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/23/10/c0b78c27298029e4454a472a1919bde20cb182dab1662cec7f2ca1dcc523/boto-2.49.0-py2.py3-none-any.whl
Collecting future (from torch>=1.3.0->stanza<2.0.0,>=1.0.0->cltk)
Collecting smmap<4,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4.0,>=3.0->cltk)
  Using cached https://files.pythonhosted.org/packages/b0/9a/4d409a6234eb940e6a78dfdfc66156e7522262f5f2fecca07dc55915952d/smmap-3.0.4-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl
Collecting botocore<1.18.0,>=1.17.16 (from boto3->smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/5c/e8/2e1d6580c3d155b4453c88d9b14a38602f67c4f1c23856c932d83e24d317/botocore-1.17.16-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3->smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.18.0,>=1.17.16->boto3->smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from botocore<1.18.0,>=1.17.16->boto3->smart-open>=1.8.1->gensim<4.0.0,>=3.8.1->cltk)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Installing collected packages: toml, joblib, regex, click, tqdm, nltk, chardet, urllib3, certifi, idna, requests, numpy, pybind11, fasttext, boltons, greek-accentuation, six, scipy, jmespath, python-dateutil, docutils, botocore, s3transfer, boto3, boto, smart-open, gensim, python-Levenshtein, future, torch, protobuf, stanza, smmap, gitdb, gitpython, cltk
Successfully installed boltons-20.2.0 boto-2.49.0 boto3-1.14.16 botocore-1.17.16 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 cltk-1.0.0a4 docutils-0.15.2 fasttext-0.9.2 future-0.18.2 gensim-3.8.3 gitdb-4.0.5 gitpython-3.1.3 greek-accentuation-1.2.0 idna-2.10 jmespath-0.10.0 joblib-0.16.0 nltk-3.5 numpy-1.19.0 protobuf-3.12.2 pybind11-2.5.0 python-Levenshtein-0.12.0 python-dateutil-2.8.1 regex-2020.6.8 requests-2.24.0 s3transfer-0.3.3 scipy-1.5.0 six-1.15.0 smart-open-2.1.0 smmap-3.0.4 stanza-1.0.1 toml-0.10.1 torch-1.5.1 tqdm-4.47.0 urllib3-1.25.9
```

And now this error running a test in REPL, I know what to do …

``` python
$ python
Python 3.7.5 (default, Oct 31 2019, 20:57:45) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cltk import NLP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltk/__init__.py", line 29, in <module>
    __version__ = get_pyproject()["version"]
  File "/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltk/__init__.py", line 23, in get_pyproject
    with open(pyproject_path, "r") as file_open:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kyle.p.johnson/.pyenv/versions/pypitest/lib/python3.7/site-packages/cltk/../../pyproject.toml'
``

**Comment by kylepjohnson** [comment]
All fixed with alpha 5:

``` python
>>> from cltk import NLP
>>> from cltk.languages.example_texts import get_example_text
>>> from cltk.core.data_types import Doc
>>> cltk_nlp = NLP(language="lat")
>>> cltk_doc = cltk_nlp.analyze(text=get_example_text("lat"))
>>> isinstance(cltk_doc, Doc)
True
>>> cltk_doc.words[5].string
'partes'
>>> cltk_doc.words[5].lemma
'pars'
```
